# Generated by Django 6.0.5 on 2026-09-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_file", models.FileField(upload_to="benchmarks/data/")),
                (
                    "kb_file",
                    models.FileField(blank=True, null=True, upload_to="benchmarks/kb/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "progress_log",
                    models.TextField(
                        blank=True, help_text="Live logs from the benchmark run"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Failure reasons or stack traces"
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured metrics from ai-benchmarking",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benchmark_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Benchmark Job",
                "verbose_name_plural": "Benchmark Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
